spring:
  application:
    name: TurboCredit_Backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: api.turbocredit_backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
documentation:
  application:
    description: "TurboCredit Backend - Vehicle Loan Management System"
    version: "1.0.0"

server:
  port: ${PORT:8082}

authorization:
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      days: 7
