spring:
  application:
    name: TurboCredit_Backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/turbocredit_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:paula123}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: api.turbocredit_backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  documentation:
    application:
      description: "TurboCredit Backend - Vehicle Loan Management System"
      version: "1.0.0"
  server:
    port: 8082
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.security: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  #firebase:
  #  credentials: ${FIREBASE_CREDENTIALS_PATH}

